# Generated by Django 5.0.2 on 2024-02-27 07:44

import django.contrib.postgres.fields
import django.db.models.deletion
import mptt.fields
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(help_text='Same Value for same Branch(Brother and Sister with their Husband and Wife)')),
                ('value', models.FloatField(help_text='Same Value for same Group (Husband and Wife)')),
                ('image', models.ImageField(help_text="Please Upload Person's Photo", upload_to='Boy')),
                ('Name', models.CharField(help_text='Enter your First Name', max_length=50)),
                ('SurName', models.CharField(help_text='Enter your Second Name', max_length=50)),
                ('Gender', models.CharField(default='Male', max_length=10)),
                ('Diffrent_Family', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is your Surname and family Name same')),
                ('Born_Place', models.CharField(help_text='Your Born Address', max_length=75)),
                ('Date_Of_Birth', models.DateField(help_text='Your Born Date', validators=[myapp.models.validate_date_format])),
                ('Status', models.CharField(choices=[('Alive', 'Alive'), ('Death', 'Death')])),
                ('Date_Of_Death', models.DateField(blank=True, help_text='Only if Person is Dead', null=True, validators=[myapp.models.validate_date_format])),
                ('Marrital_Status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried'), ('Divorce', 'Divorce')])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Father', to='myapp.boy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(help_text='Same Value for same Branch(Brother and Sister with their Husband and Wife)')),
                ('value', models.FloatField(help_text='Same Value for same Group (Husband and Wife)')),
                ('image', models.ImageField(help_text="Please Upload Person's Photo", upload_to='Girl')),
                ('Name', models.CharField(help_text='Enter your First Name', max_length=50)),
                ('SurName', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='For married girls write both Surname using (,)', max_length=75), size=None)),
                ('Gender', models.CharField(default='Female', editable=False, max_length=10)),
                ('Diffrent_Family', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='When is your Surname and family Name same')),
                ('Born_Place', models.CharField(help_text='Your Born Address', max_length=75)),
                ('Date_Of_Birth', models.DateField(help_text='Your Born Date', validators=[myapp.models.validate_date_format])),
                ('Status', models.CharField(choices=[('Alive', 'Alive'), ('Death', 'Death')])),
                ('Date_Of_Death', models.DateField(blank=True, help_text='Only if Person is Dead', null=True, validators=[myapp.models.validate_date_format])),
                ('Marrital_Status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried'), ('Divorce', 'Divorce')])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dady', to='myapp.boy')),
                ('Husband', models.ManyToManyField(blank=True, related_name='husband', to='myapp.boy')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='myapp.girl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='boy',
            name='Mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momy', to='myapp.girl'),
        ),
        migrations.AddField(
            model_name='boy',
            name='Wife',
            field=models.ManyToManyField(blank=True, related_name='wife', to='myapp.girl'),
        ),
    ]
